### ISSUE TITLE
Input loses focus after dropdown appears

### ISSUE THREAD

**Issue by Xyzor** [maxkordiyak/react-native-dropdown-autocomplete#4]
Currently after search, it shows the result list, but loses the focus on the input.

Is there a solution to focus the selected input after search or to pass down a ref prop?

**Comment by maxkordiyak** [comment]
it is not possible as long as result list is a modal. you can't interact with input because it is outside modal

**Comment by UdyogaG** [comment]
there is have any way to keep open the keyboard without hiding the keyboard.

**Comment by PaitoAnderson** [comment]
Reopening for further discussion as it's a pretty serious drawback for this library.

**Comment by PaitoAnderson** [comment]
Took a look at this briefly, and came too few conclusions...

- You can't make a pure javascript React Component overlap another Component unless they are adjacent (using zIndex), this doesn't work because you can't control if the component it will be overlapping is adjacent to the `<Autocomplete />` component or not.
- Using `<Modal />` to make an overlapping component hides the keyboard immediately as already pointed out.

In order to solve this we probably need to take one of these approaches...

1) Expand the `<Autocomplete />` component when showing the dropdown pushing anything below it down instead of trying to overlap it, looks less cool but resolves a significant issue imo.
2) Perhaps do something with native code which would add significant complexity to this library.

**Comment by PaitoAnderson** [comment]
Created a PR for expanding the component, only minor issue is if you use this component in a ScrollView/FlatList be sure to set `keyboardShouldPersistTaps="always"` so you can tap on the results when the keyboard is still visible.
